export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_QUIZZES_SUCCESS = 'LOAD_QUIZZES_SUCCESS';
export const CREATE_QUIZ_SUCCESS = 'CREATE_QUIZ_SUCCESS';
export const UPDATE_QUIZ_SUCCESS = 'UPDATE_QUIZ_SUCCESS';
export const LOAD_RANDOM_QUIZ_SUCCESS = 'LOAD_RANDOM_QUIZ_SUCCESS';

export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const WEBSOCKET_LOGIN_SUCCESS = 'WEBSOCKET_LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_ADMIN_SUCCESS = 'GET_ADMIN_SUCCESS';

export const CREATE_MATCH_SUCCESS = 'CREATE_MATCH_SUCCESS';
export const UPDATE_MATCH_SUCCESS = 'UPDATE_MATCH_SUCCESS';
export const LOAD_MATCHES_SUCCESS = 'LOAD_MATCHES_SUCCESS';

export const START_MATCH_SUCCESS = 'START_MATCH_SUCCESS';
